site: Hee Suk Yoon

url: https://hee-suk-yoon.github.io
baseurl: ""


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-sitemap

  
